### ISSUE TITLE
Question about App Service SDK

### ISSUE THREAD

**Issue by itoledo** [HMS-Core/hms-xamarin-bindings#1]
Hi!
First of all, many thanks for the official Huawei HMS nugets! been doing bindings on my own repo since last year and updates were a hassle.

Yesterday I sent an updated app to AppGallery and got a comment on the approval notice about the "update detection interface":

> [Description]:We found that the HMS does not invoke the update detection interface after the app was launched.The publishing in Mainland China and other countries or regions you have chosen to publish has been affected until all the requirements above are met. For more information. For more information, please refer to: https://developer.huawei.com/consumer/cn/doc/development/AppGallery-connect-Guides/appgallerykit-checklist

Searching in the official documentation there is mention of JosApps.getAppUpdateClient() on the "appservice" SDK, which doesn't seem to be available for Xamarin: [link](https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/appgallerykit-app-update-0000001055118286)

So, is there another way to implement that functionality? Is it available on one of the bindings/kits? Searching thru the code on this repo doesn't show hits for JosApps or AppUpdate.

Thanks again for your hard work!
Ivan

**Comment by ahmetercek** [comment]
Hello itoledo,

Currently "appservice" sdk is not available for Xamarin platform. It's not in plan now. But you can create binding library to use this sdk in Xamarin.
You can find native demo project here : https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/appgallerykit-getting-started-0000001055756858#EN-US_TOPIC_0000001055756858__section33939181109

Creating binding library :
https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/binding-an-aar

Thanks for your feedback.
