### ISSUE TITLE
PushKit - Didn't find class "com.huawei.hms.framework.common.EmuiUtil"

### ISSUE THREAD

**Issue by leonardbarbu** [HMS-Core/hms-xamarin-bindings#12]
Hello,
After facing this issue into a production app, I downloaded the [PushKitDemo](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Examples-V1/xamarin-sample-code-0000001050138645-V1) on my Mac and I am getting the same issue.
I am testing on a Huawei P40 Lite. I am getting the error on both debug and release modes, so it's not related to proguard.cfg.

On this post on [StackOverflow](https://stackoverflow.com/questions/70524032/failed-resolution-of-lcom-huawei-hms-framework-common-emuiutil) some guys said to downgrade Huawei.Hms.Push to the lowest available version 5.0.4.302, but I made the update of the NuGet package from the old one 5.0.4.302 to the current one (6.1.0.304) - because of a security warning in Google Play console ([Implicit PendingIntent](https://support.google.com/faqs/answer/10437428) on com.huawei.hms.support.api.push.pushselfshow.prepare.PushNotification.showNotification

Thanks.

<img width="1182" alt="Captură de ecran din 2022-11-29 la 14 08 41" src="https://user-images.githubusercontent.com/38347156/205688930-0f577d69-82d2-4c98-af05-d716498b87cb.png">

**Comment by xuxiapu** [comment]
@leonardbarbu Dear developer,
It is recommended that you install the "Huawei. Hms. NetworkFrameworkCompat" component and try again. If you have other questions, please contact us.

**Comment by leonardbarbu** [comment]
> @leonardbarbu Dear developer, It is recommended that you install the "Huawei. Hms. NetworkFrameworkCompat" component and try again. If you have other questions, please contact us.

It's working. Thanks!
