### ISSUE TITLE
HiAnalyticsInstance.AAID returning null value

### ISSUE THREAD

**Issue by Kwiyos** [HMS-Core/hms-xamarin-bindings#3]
I've tried to run HiAnalyticsDemo with my own project id and agconnect-services.json and it worked, the event is showing in HMS Console App debugging page.
However I can't get it to work on my own project somehow, I've followed the guides step by step and also referencing the codes from HiAnalyticsDemo but its not working.

One thing that I noticed thought, is that the **AAID** value from HiAnalyticsInstance object is actually **null** when I try to run it in my project (_when I debug from HiAnalyticsDemo its not null_)
![aaid](https://user-images.githubusercontent.com/46819017/130214443-bce26bff-9092-42e5-881b-9356980563b9.png)

Any idea what's causing this to happen? 
Thank in advance

**Comment by stugcearar** [comment]
Helllo,

Can you please send the detailed output? And also did you use any other HMS or AGC NuGet in your project?

**Comment by Kwiyos** [comment]
> Helllo,
> 
> Can you please send the detailed output? And also did you use any other HMS or AGC NuGet in your project?

Hi,

Not sure which output you need and how do I get it

The other NuGet I used are
-Huawei.Hms.Safetydetect
-Huawei.Hms.Push
-Huawei.Agconnect.Crash

**Comment by stugcearar** [comment]
First, please do following; 

1. Tools –> Options –>Xamarin 
2. Set the Xamarin Diagnostics output verbosity to **Diagnostics**

After run the project and getting null to **AAID**, copy output from the Output window to a txt file and send here please.

**Comment by Kwiyos** [comment]
> First, please do following in Visual Studio;
> 
> 1. Tools –> Options –>Xamarin
> 2. Set the Xamarin Diagnostics output verbosity to **Diagnostics**
> 
> After run the project and getting null to **AAID**, copy output from the Output window to a txt file and send here please.

[ShowOutputFrom Xamarin Diagnostics.txt](https://github.com/HMS-Core/hms-xamarin-bindings/files/7037720/ShowOutputFrom.Xamarin.Diagnostics.txt)

**Comment by stugcearar** [comment]
> > First, please do following in Visual Studio;
> > 
> > 1. Tools –> Options –>Xamarin
> > 2. Set the Xamarin Diagnostics output verbosity to **Diagnostics**
> > 
> > After run the project and getting null to **AAID**, copy output from the Output window to a txt file and send here please.
> 
> [ShowOutputFrom Xamarin Diagnostics.txt](https://github.com/HMS-Core/hms-xamarin-bindings/files/7037720/ShowOutputFrom.Xamarin.Diagnostics.txt)

Can you send debug output like below image?

![debug](https://user-images.githubusercontent.com/12747384/130591495-cb130bfe-c798-4fe0-bb99-ddb6be2aac01.png)

**Comment by Kwiyos** [comment]
> > > First, please do following in Visual Studio;
> > > 
> > > 1. Tools –> Options –>Xamarin
> > > 2. Set the Xamarin Diagnostics output verbosity to **Diagnostics**
> > > 
> > > After run the project and getting null to **AAID**, copy output from the Output window to a txt file and send here please.
> > 
> > 
> > [ShowOutputFrom Xamarin Diagnostics.txt](https://github.com/HMS-Core/hms-xamarin-bindings/files/7037720/ShowOutputFrom.Xamarin.Diagnostics.txt)
> 
> Can you copy and send debug output please?
> 
> ![debug](https://user-images.githubusercontent.com/12747384/130591653-2a14f817-cf69-4d3b-be59-057fb21e5d4b.png)

Opps, my bad

[Output Debug.txt](https://github.com/HMS-Core/hms-xamarin-bindings/files/7038183/Output.Debug.txt)

There's a lots of stuff in Debug output so I just try to copy what I thought is relevant
