### ISSUE TITLE
There is no implementation of the "ReadSmsManager.StartConsent ()" function.

### ISSUE THREAD

**Issue by monster74** [HMS-Core/hms-xamarin-bindings#4]
nuget Huawei.Hms.Hwid 5.0.3.302
There is no implementation of the "ReadSmsManager.StartConsent ()" function.

**Comment by HamdiAktar** [comment]
Hi @monster74 

The current version of Account plugin (5.0.3.303) does not include startConsent method. We plan to release the updated version soon.
You can add the repository to your watchlist to get the latest updates.

Regards.

**Comment by monster74** [comment]
Thanks. I am waiting for an updated version.
