### ISSUE TITLE
Huawei.Hms.Hwid 5.0.3.303

### ISSUE THREAD

**Issue by monster74** [HMS-Core/hms-xamarin-bindings#5]
Hello.
On the Huawei website, the current version of the plugin is listed as 5.0.3.303. On the website "nuget.org" the current version of the plugin is specified 5.0.3.302. There will be an update to 5.0.3.303 on "nuget.org"?
[Huawei](https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-Library/xamarin-sdk-download-0000001050768441)
[nuget.org](https://www.nuget.org/packages/Huawei.Hms.Hwid/)

**Comment by tugcearar** [comment]
Hello @monster74 ,

It has been increased to distinguish the version nuget and the binding library on the website. However, the same native version (ie 5.0.3.302) was used in 5.0.3.303 and 5.0.3.302.

**Comment by monster74** [comment]
When will the update with the "ReadSmsManager.StartConsent ()" function be released, will the nuget package version be updated?

**Comment by stugcearar** [comment]
Updated version will be released at the end of October.
